param([switch]$Check)
$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
$catalogPath = Join-Path $projectRoot 'src\localization\strings.json'
$catalog = Get-Content -LiteralPath $catalogPath -Raw | ConvertFrom-Json -AsHashtable
$languages = @('en','zh-Hans','zh-Hant','ja','fr','it','de','es','pt-BR','ru','ko','id','es-419','th','tr','vi','pl')
$requiredKeys = @('machine_name','description','receive','payment_prompt','selected','spend_receive','obtain_tooltip','elements')
$elementIds = @('Electric','Fire','Water','Grass','Ground','Ice','Dragon','Dark','Neutral')

if ($catalog.Count -ne $languages.Count) { throw "Expected 17 languages, found $($catalog.Count)" }
function Write-Utf8([string]$path, [string]$text) {
    $text = $text.Replace("`r`n", "`n").TrimEnd("`r", "`n") + "`n"
    if ($Check) {
        if (!(Test-Path -LiteralPath $path) -or [IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $text) {
            throw "Generated file differs: $path"
        }
        return
    }
    [IO.Directory]::CreateDirectory((Split-Path -Parent $path)) | Out-Null
    [IO.File]::WriteAllText($path, $text, [Text.UTF8Encoding]::new($false))
}
function Lua-Quote([string]$value) {
    return '"' + $value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n') + '"'
}

$lua = [Collections.Generic.List[string]]::new()
$lua.Add('-- Generated by tools/generate_localizations.ps1; edit src/localization/strings.json.')
$lua.Add('local M = {}')
$lua.Add('M.languages = {')
foreach ($language in $languages) { $lua.Add("    $(Lua-Quote $language),") }
$lua.Add('}')
$lua.Add('M.aliases = {')
$lua.Add('    ["zh-tw"] = "zh-Hant",')
$lua.Add('    ["zh-cn"] = "zh-Hans",')
$lua.Add('    ["es-es"] = "es",')
$lua.Add('    ["global"] = "en",')
$lua.Add('}')
$lua.Add('M.data = {')

foreach ($language in $languages) {
    $strings = $catalog[$language]
    foreach ($key in $requiredKeys) {
        if (!$strings.ContainsKey($key) -or [string]::IsNullOrWhiteSpace([string]$strings[$key])) { throw "Missing string: $language/$key" }
    }
    if ($strings.elements.Count -ne $elementIds.Count) { throw "Expected 9 elements: $language" }
    foreach ($element in $elementIds) {
        if (!$strings.elements.ContainsKey($element) -or [string]::IsNullOrWhiteSpace([string]$strings.elements[$element])) { throw "Missing element: $language/$element" }
    }
    foreach ($pattern in @('360[,. ]?000')) {
        if ([string]$strings.description -notmatch $pattern) { throw "Missing power value: $language/$pattern" }
    }
    foreach ($token in @('{source}','{target}')) {
        if (!$strings.spend_receive.Contains($token)) { throw "Missing exchange placeholder: $language/$token" }
    }
    if (!$strings.obtain_tooltip.Contains('{element}')) { throw "Missing tooltip placeholder: $language" }
    $lua.Add("    [$(Lua-Quote $language)] = {")
    foreach ($key in @('machine_name','description','receive','payment_prompt','selected','spend_receive','obtain_tooltip')) {
        $lua.Add("        $key = $(Lua-Quote ([string]$strings[$key])),")
    }
    $lua.Add('        elements = {')
    foreach ($element in $elementIds) { $lua.Add("            [$(Lua-Quote $element)] = $(Lua-Quote ([string]$strings.elements[$element])),") }
    $lua.Add('        },')
    $lua.Add('    },')

    $palSchema = [ordered]@{
        DT_MapObjectNameText = @{ "MAPOBJECT_NAME_PAE_ExchangePrototype" = [string]$strings.machine_name }
        DT_BuildObjectDescText = @{ "BUILDOBJECT_DESC_PAE_ExchangePrototype" = [string]$strings.description }
        DT_TechnologyNameText = @{ "NAME_RECIPE_PAE_ExchangePrototype" = [string]$strings.machine_name }
        DT_TechnologyDescText = @{ "DESC_RECIPE_PAE_ExchangePrototype" = [string]$strings.description }
    } | ConvertTo-Json -Depth 6
    $translationPath = Join-Path $projectRoot "src\PalAwakeningExchangePrototype\translations\$language\strings.json"
    Write-Utf8 $translationPath $palSchema
    $alias = @{ 'zh-Hant' = 'zh-TW'; 'zh-Hans' = 'zh-CN'; 'es' = 'es-ES' }[$language]
    if ($alias) { Write-Utf8 (Join-Path $projectRoot "src\PalAwakeningExchangePrototype\translations\$alias\strings.json") $palSchema }
    if ($language -eq 'en') { Write-Utf8 (Join-Path $projectRoot 'src\PalAwakeningExchangePrototype\translations\global\strings.json') $palSchema }
}
$lua.Add('}')
$lua.Add('')
$lua.Add('function M.resolve(language)')
$lua.Add('    if type(language) ~= "string" then language = tostring(language or "en") end')
$lua.Add('    language = language:gsub("_", "-"):lower()')
$lua.Add('    if M.aliases[language] then return M.aliases[language] end')
$lua.Add('    for _, code in ipairs(M.languages) do')
$lua.Add('        if code:lower() == language then return code end')
$lua.Add('    end')
$lua.Add('    return "en"')
$lua.Add('end')
$lua.Add('')
$lua.Add('function M.entry(language)')
$lua.Add('    return M.data[M.resolve(language)] or M.data.en')
$lua.Add('end')
$lua.Add('')
$lua.Add('function M.format(language, key, source, target)')
$lua.Add('    local text = M.entry(language)[key] or M.data.en[key]')
$lua.Add('    if source then text = text:gsub("{source}", source) end')
$lua.Add('    if target then text = text:gsub("{target}", target) end')
$lua.Add('    return text')
$lua.Add('end')
$lua.Add('')
$lua.Add('return M')
Write-Utf8 (Join-Path $projectRoot 'src\AwakeningCrystalConverterUI\Scripts\locale.lua') ($lua -join "`n")
Write-Output "17 languages validated and generated. Check=$Check"
